#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects -mindepth 1 -maxdepth 1 -type d | fzf)
    is_project=true
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
    tmux new-session -ds dotfiles -c ~/projects/dotfiles
    tmux new-session -ds notes -c ~/notes
    tmux new-session -ds terminal -c ~
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected

    if [[ $is_project ]]; then
        tmux rename-window -t $selected_name run
        tmux new-window -t "$selected_name:2" -c $selected -n edit
        tmux new-window -t "$selected_name:3" -c $selected -n terminal
    fi
fi

if [[ -z $TMUX ]]; then
    tmux attach
else
    tmux switch-client -t $selected_name
fi
